In [1]:
import pandas as pd
import numpy as np
import datetime
import matplotlib
import json
import requests
import time
from tqdm import tqdm

In [2]:
from pandas_datareader import data, wb
import pandas_datareader.data as web

In [3]:
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 1000)

In [ ]:
# ---------------------

In [ ]:

close_px = df['Adj Close']
mavg = close_px.rolling(window=100).mean()

In [ ]:
mavg

In [ ]:
rets = close_px / close_px.shift(1) - 1

In [ ]:
rets.plot(label='return')

In [ ]:
dfcomp = web.DataReader(stock_list,'yahoo',start=start,end=end)['Adj Close']

# S&P500 Stock Collection (Wikipedia)

In [4]:
wiki = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')

pd.set_option('display.max_rows', 505)

wiki1 = wiki[0]

wiki1

tickers = wiki1['Symbol']

ticker_list = list(wiki1['Symbol'])

ticker_list[69] = 'BRK-B'
ticker_list[81] = 'BF-B'

ticker_list

tickers_marketwatch=list(wiki1['Symbol'])

tickers_marketwatch

['MMM',
 'ABT',
 'ABBV',
 'ABMD',
 'ACN',
 'ATVI',
 'ADBE',
 'AMD',
 'AAP',
 'AES',
 'AFL',
 'A',
 'APD',
 'AKAM',
 'ALK',
 'ALB',
 'ARE',
 'ALXN',
 'ALGN',
 'ALLE',
 'AGN',
 'ADS',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AAL',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'ABC',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'ANSS',
 'ANTM',
 'AON',
 'AOS',
 'APA',
 'AIV',
 'AAPL',
 'AMAT',
 'APTV',
 'ADM',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVB',
 'AVY',
 'BKR',
 'BLL',
 'BAC',
 'BK',
 'BAX',
 'BDX',
 'BRK.B',
 'BBY',
 'BIIB',
 'BLK',
 'BA',
 'BKNG',
 'BWA',
 'BXP',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BF.B',
 'CHRW',
 'COG',
 'CDNS',
 'CPB',
 'COF',
 'CPRI',
 'CAH',
 'KMX',
 'CCL',
 'CARR',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'CE',
 'CNC',
 'CNP',
 'CTL',
 'CERN',
 'CF',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CI',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CTXS',
 'CLX',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'CL',
 'CMCSA',
 'CMA',
 'CAG',
 'CXO',
 'COP',
 'ED',
 'STZ',
 'COO',
 'CPRT',
 'GLW',
 'CTVA',
 'COST',
 'COTY',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHI',
 'DHR',
 'DRI',
 'DVA',
 'DE',
 'DAL',
 'XRAY',
 'DVN',
 'FANG',
 'DLR',
 'DFS',
 'DISCA',
 'DISCK',
 'DISH',
 'DG',
 'DLTR',
 'D',
 'DOV',
 'DOW',
 'DTE',
 'DUK',
 'DRE',
 'DD',
 'DXC',
 'ETFC',
 'EMN',
 'ETN',
 'EBAY',
 'ECL',
 'EIX',
 'EW',
 'EA',
 'EMR',
 'ETR',
 'EOG',
 'EFX',
 'EQIX',
 'EQR',
 'ESS',
 'EL',
 'EVRG',
 'ES',
 'RE',
 'EXC',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FB',
 'FAST',
 'FRT',
 'FDX',
 'FIS',
 'FITB',
 'FE',
 'FRC',
 'FISV',
 'FLT',
 'FLIR',
 'FLS',
 'FMC',
 'F',
 'FTNT',
 'FTV',
 'FBHS',
 'FOXA',
 'FOX',
 'BEN',
 'FCX',
 'GPS',
 'GRMN',
 'IT',
 'GD',
 'GE',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GL',
 'GPN',
 'GS',
 'GWW',
 'HRB',
 'HAL',
 'HBI',
 'HOG',
 'HIG',
 'HAS',
 'HCA',
 'PEAK',
 'HP',
 'HSIC',
 'HSY',
 'HES',
 'HPE',
 'HLT',
 'HFC',
 'HOLX',
 'HD',
 'HON',
 'HRL',
 'HST',
 'HWM',
 'HPQ',
 'HUM',
 'HBAN',
 'HII',
 'IEX',
 'IDXX',
 'INFO',
 'ITW',
 'ILMN',
 'INCY',
 'IR',
 'INTC',
 'ICE',
 'IBM',
 'IP',
 'IPG',
 'IFF',
 'INTU',
 'ISRG',
 'IVZ',
 'IPGP',
 'IQV',
 'IRM',
 'JKHY',
 'J',
 'JBHT',
 'SJM',
 'JNJ',
 'JCI',
 'JPM',
 'JNPR',
 'KSU',
 'K',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KLAC',
 'KSS',
 'KHC',
 'KR',
 'LB',
 'LHX',
 'LH',
 'LRCX',
 'LW',
 'LVS',
 'LEG',
 'LDOS',
 'LEN',
 'LLY',
 'LNC',
 'LIN',
 'LYV',
 'LKQ',
 'LMT',
 'L',
 'LOW',
 'LYB',
 'MTB',
 'MRO',
 'MPC',
 'MKTX',
 'MAR',
 'MMC',
 'MLM',
 'MAS',
 'MA',
 'MKC',
 'MXIM',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MHK',
 'TAP',
 'MDLZ',
 'MNST',
 'MCO',
 'MS',
 'MOS',
 'MSI',
 'MSCI',
 'MYL',
 'NDAQ',
 'NOV',
 'NTAP',
 'NFLX',
 'NWL',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NLSN',
 'NKE',
 'NI',
 'NBL',
 'JWN',
 'NSC',
 'NTRS',
 'NOC',
 'NLOK',
 'NCLH',
 'NRG',
 'NUE',
 'NVDA',
 'NVR',
 'ORLY',
 'OXY',
 'ODFL',
 'OMC',
 'OKE',
 'ORCL',
 'OTIS',
 'PCAR',
 'PKG',
 'PH',
 'PAYX',
 'PAYC',
 'PYPL',
 'PNR',
 'PBCT',
 'PEP',
 'PKI',
 'PRGO',
 'PFE',
 'PM',
 'PSX',
 'PNW',
 'PXD',
 'PNC',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PEG',
 'PSA',
 'PHM',
 'PVH',
 'QRVO',
 'PWR',
 'QCOM',
 'DGX',
 'RL',
 'RJF',
 'RTX',
 'O',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RHI',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'SPGI',
 'CRM',
 'SBAC',
 'SLB',
 'STX',
 'SEE',
 'SRE',
 'NOW',
 'SHW',
 'SPG',
 'SWKS',
 'SLG',
 'SNA',
 'SO',
 'LUV',
 'SWK',
 'SBUX',
 'STT',
 'STE',
 'SYK',
 'SIVB',
 'SYF',
 'SNPS',
 'SYY',
 'TMUS',
 'TROW',
 'TTWO',
 'TPR',
 'TGT',
 'TEL',
 'FTI',
 'TFX',
 'TXN',
 'TXT',
 'TMO',
 'TIF',
 'TJX',
 'TSCO',
 'TT',
 'TDG',
 'TRV',
 'TFC',
 'TWTR',
 'TSN',
 'UDR',
 'ULTA',
 'USB',
 'UAA',
 'UA',
 'UNP',
 'UAL',
 'UNH',
 'UPS',
 'URI',
 'UHS',
 'UNM',
 'VFC',
 'VLO',
 'VAR',
 'VTR',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VIAC',
 'V',
 'VNO',
 'VMC',
 'WRB',
 'WAB',
 'WMT',
 'WBA',
 'DIS',
 'WM',
 'WAT',
 'WEC',
 'WFC',
 'WELL',
 'WDC',
 'WU',
 'WRK',
 'WY',
 'WHR',
 'WMB',
 'WLTW',
 'WYNN',
 'XEL',
 'XRX',
 'XLNX',
 'XYL',
 'YUM',
 'ZBRA',
 'ZBH',
 'ZION',
 'ZTS']

# Stock Data Pull (Yahoo!)

In [ ]:
now = datetime.datetime.now()
start_year = int(now.strftime('%Y'))-5
end_year = int(now.strftime('%Y'))
day = int(now.strftime('%d'))
month = int(now.strftime('%m'))
start = datetime.datetime(start_year, month, day)
end = datetime.datetime(end_year, month, day)

def data_pull(tick):
    df = web.DataReader(f'{tick}', 'yahoo', start, end)
    df['Company']= f'{tick}'
    return df

## Establishing Dates

In [18]:
now = datetime.datetime.now()
start_year = int(now.strftime('%Y'))#-10
end_year = int(now.strftime('%Y'))
day = int(now.strftime('%d'))
month = int(now.strftime('%m'))
start = datetime.datetime(start_year, month, day)
end = datetime.datetime(end_year, month, day)

start_year_1 = int(now.strftime('%Y'))-1
end_year_1 = int(now.strftime('%Y'))-1
day = int(now.strftime('%d'))
month = int(now.strftime('%m'))
start_1 = datetime.datetime(start_year_1, month, day)
end_1 = datetime.datetime(end_year_1, month, day)
day_of_w = start_1.weekday()
if day_of_w == 5:
    start_1 = start_1 + datetime.timedelta(days=2)
    end_1 = end_1 + datetime.timedelta(days=2)
elif day_of_w == 6:
    start_1 = start_1 + datetime.timedelta(days=1)
    end_1 = end_1 + datetime.timedelta(days=1)


start_year_2 = int(now.strftime('%Y'))-2
end_year_2 = int(now.strftime('%Y'))-2
day = int(now.strftime('%d'))
month = int(now.strftime('%m'))
start_2 = datetime.datetime(start_year_2, month, day)
end_2 = datetime.datetime(end_year_2, month, day)
day_of_w = start_2.weekday()
if day_of_w == 5:
    start_2 = start_2 + datetime.timedelta(days=2)
    end_2 = end_2 + datetime.timedelta(days=2)
elif day_of_w == 6:
    start_2 = start_2 + datetime.timedelta(days=1)
    end_2 = end_2 + datetime.timedelta(days=1)

start_year_3 = int(now.strftime('%Y'))-3
end_year_3 = int(now.strftime('%Y'))-3
day = int(now.strftime('%d'))
month = int(now.strftime('%m'))
start_3 = datetime.datetime(start_year_3, month, day)
end_3 = datetime.datetime(end_year_3, month, day)
day_of_w = start_3.weekday()
if day_of_w == 5:
    start_3 = start_3 + datetime.timedelta(days=2)
    end_3 = end_3 + datetime.timedelta(days=2)
elif day_of_w == 6:
    start_3 = start_3 + datetime.timedelta(days=1)
    end_3 = end_3 + datetime.timedelta(days=1)

start_year_4 = int(now.strftime('%Y'))-4
end_year_4 = int(now.strftime('%Y'))-4
day = int(now.strftime('%d'))
month = int(now.strftime('%m'))
start_4 = datetime.datetime(start_year_4, month, day)
end_4 = datetime.datetime(end_year_4, month, day)
day_of_w = start_4.weekday()
if day_of_w == 5:
    start_4= start_4 + datetime.timedelta(days=2)
    end_4= end_4 + datetime.timedelta(days=2)
elif day_of_w == 6:
    start_4= start_4 + datetime.timedelta(days=1)
    end_4= end_4 + datetime.timedelta(days=1)
    
start_year_5 = int(now.strftime('%Y'))-5
end_year_5 = int(now.strftime('%Y'))-5
day = int(now.strftime('%d'))
month = int(now.strftime('%m'))
start_5 = datetime.datetime(start_year_5, month, day)
end_5 = datetime.datetime(end_year_5, month, day)
day_of_w = start_5.weekday()
if day_of_w == 5:
    start_5= start_5 + datetime.timedelta(days=2)
    end_5= end_5 + datetime.timedelta(days=2)
elif day_of_w == 6:
    start_5= start_5 + datetime.timedelta(days=1)
    end_5= end_5 + datetime.timedelta(days=1)

## Price Pull

In [19]:
def data_pull(tick):
    df0 = web.DataReader(f'{tick}', 'yahoo', start, end)
    df1 = web.DataReader(f'{tick}', 'yahoo', start_1, end_1)
    df2 = web.DataReader(f'{tick}', 'yahoo', start_2, end_2)
    df3 = web.DataReader(f'{tick}', 'yahoo', start_3, end_3)
    df4 = web.DataReader(f'{tick}', 'yahoo', start_4, end_4)
    df5 = web.DataReader(f'{tick}', 'yahoo', start_5, end_5)
    frames = [df0, df1, df2, df3, df4, df5]
    df=pd.concat(frames)
    df['Company']= f'{tick}'
    return df

In [ ]:
stock_df_list = []
for t in ticker_list: 
    try:
        print(t)
        tick = f'{t}'
        stock = data_pull(f'{t}')
        stock_df_list.append(stock)
        time.sleep(1) 
    except:
        print(f'unable to pull{t}')
        # lambda replace "." with "-"

len(stock_df_list)

In [ ]:
stock_df_list[0]

In [20]:
#Testing Purposes
stock_df_list = []
stock = data_pull('ABT')
stock_df_list.append(stock)

In [21]:
stock_df_list[0]

,High,Low,Open,Close,Volume,Adj Close,Company
Date,,,,,,,
2020-04-29,93.040001,91.070503,92.089996,92.480003,4057199,92.480003,ABT
2019-04-29,78.629997,77.580002,78.559998,78.269997,4355000,77.013832,ABT
2018-04-30,59.799999,58.099998,59.759998,58.130001,6096100,56.216137,ABT
2017-05-01,43.660000,43.320000,43.570000,43.480000,5119100,41.217037,ABT
2016-04-29,40.380001,38.580002,40.369999,38.900002,30646800,35.964439,ABT
2015-04-29,47.639999,46.880001,47.279999,47.169998,3566600,42.619190,ABT

# Stock Financial Statement Pull (MarketWatch)

- EPS: (Earning Per Share) is the portion of a company’s profit allocated to each share of common stock
- ROE: (Return of Equity): is a measure of financial performance calculated by dividing net income by shareholders’ equity
- ROA: (Return of Assets) is an indicator of how profitable a company is relative to its total assets
- Long Term Debt: would include company bond issues or long-term leases that have been capitalized on a firm’s balance sheet
- Total Income
- Debt to Equity: is used to evaluate a company’s financial leverage
- Interest Coverage Ratio: is used to determine how easily a company can pay their interest expenses on outstanding debt
-----------
- PE: (Price to Earnings Ratio)
- PB: (Price to Book Ratio)
- PEG: (Price/EPS)/EPS Growth
- * NOT USING * Graham's Blended Multiplier (GBM): PE X PB [resulting number should be < 22.5]

## Updated Financials Function

In [ ]:
inc_st = pd.read_html('https://www.marketwatch.com/investing/stock/mmm/financials')
income_state = pd.DataFrame(inc_st[1])
income_state = income_state.transpose()

In [ ]:
new_header = income_state.iloc[0]
income_state = income_state[1:]
income_state.columns = new_header

In [ ]:
income_state

In [ ]:
eps = income_state['EPS (Basic)']
eps = eps.to_frame()
eps_growth = income_state['EPS (Basic) Growth']
eps_growth = eps_growth.to_frame()
net_income =  income_state['Net Income']
net_income = net_income.to_frame()
interest_expense = income_state['Interest Expense']
interest_expense = interest_expense.to_frame()
EBITDA = income_state['EBITDA']
EBITDA = EBITDA.to_frame()

In [ ]:
i_s=eps.join(eps_growth)
i_s = i_s.join(net_income)
i_s = i_s.join(interest_expense)
i_s = i_s.join(EBITDA)
i_s = i_s.rename(columns={'EPS (Basic)':'eps', 'EPS (Basic) Growth':'eps_growth', 'Net Income': 'net_income', 'Interest Expense': 'interest_expense', 'EBITDA': 'ebitda'})
i_s=i_s.drop('5-year trend')

In [ ]:
i_s

In [ ]:
bal_sh = pd.read_html('https://www.marketwatch.com/investing/stock/mmm/financials/balance-sheet')

In [ ]:
balance_sheet1 = pd.DataFrame(bal_sh[1])
balance_sheet1 = balance_sheet1.transpose()
balance_sheet2 = pd.DataFrame(bal_sh[2])
balance_sheet2 = balance_sheet2.transpose()

In [ ]:
new_header1 = balance_sheet1.iloc[0]
balance_sheet1 = balance_sheet1[1:]
balance_sheet1.columns = new_header1

new_header2 = balance_sheet2.iloc[0]
balance_sheet2 = balance_sheet2[1:]
balance_sheet2.columns = new_header2

In [ ]:
balance_sheet1["Total Assets"]

In [ ]:
shareholder_equity = balance_sheet2["Total Shareholders' Equity"]
shareholder_equity = shareholder_equity.to_frame()
longterm_debt = balance_sheet2["Long-Term Debt"]
longterm_debt = longterm_debt.to_frame()
total_assets = balance_sheet1["Total Assets"]
total_assets = total_assets.to_frame()

In [ ]:
b_s=shareholder_equity.join(longterm_debt)
b_s = b_s.join(total_assets)
b_s = b_s.rename(columns={"Total Shareholders' Equity":'shareholder_equity', '"Long-Term Debt"':'longterm_debt', "Total Assets": 'total_assets'})
b_s=b_s.drop('5-year trend')

In [ ]:
b_s

In [ ]:
financials=i_s.merge(b_s, left_index=True, right_index=True)

In [ ]:
financials

# --------

In [304]:
def financial_scrubber(ticker_list):
    """creates a dataframe of stock essential financal information and ratios"""
    financials_list=[]
    collected_stocks=[]
    trouble_stocks=[]   
    for ticker in ticker_list:
        try:
            inc_st = pd.read_html(f'https://www.marketwatch.com/investing/stock/{ticker}/financials')
            income_state = pd.DataFrame(inc_st[1])
            income_state = income_state.transpose()
            new_header = income_state.iloc[0]
            income_state = income_state[1:]
            income_state.columns = new_header
            eps = income_state['EPS (Basic)']
            eps = eps.to_frame()
            eps_growth = income_state['EPS (Basic) Growth']
            eps_growth = eps_growth.to_frame()
            net_income =  income_state['Net Income']
            net_income = net_income.to_frame()
            interest_expense = income_state['Interest Expense']
            interest_expense = interest_expense.to_frame()
            EBITDA = income_state['EBITDA']
            EBITDA = EBITDA.to_frame()
            #
            outstanding_shares = income_state['Basic Shares Outstanding']
            outstanding_shares = outstanding_shares.to_frame()
            ebitda_growth_rate = income_state['EBITDA Growth']
            ebitda_growth_rate = ebitda_growth_rate.to_frame()
            #
            i_s=eps.join(eps_growth)
            i_s = i_s.join(net_income)
            i_s = i_s.join(interest_expense)
            i_s = i_s.join(EBITDA)
            #
            i_s = i_s.join(outstanding_shares)
            i_s = i_s.join(ebitda_growth_rate)
            #
            i_s = i_s.rename(columns={'EPS (Basic)':'eps', 'EPS (Basic) Growth':'eps_growth', 'Net Income': 'net_income', 'Interest Expense': 'interest_expense', 'EBITDA': 'ebitda', 'Basic Shares Outstanding': 'outstanding_shares', 'EBITDA Growth':'ebitda_growth_rate'})
            i_s=i_s.drop('5-year trend')


            bal_sh= pd.read_html(f'https://www.marketwatch.com/investing/stock/{ticker}/financials/balance-sheet')
            balance_sheet1 = pd.DataFrame(bal_sh[1])
            balance_sheet1 = balance_sheet1.transpose()
            balance_sheet2 = pd.DataFrame(bal_sh[2])
            balance_sheet2 = balance_sheet2.transpose()
            new_header1 = balance_sheet1.iloc[0]
            balance_sheet1 = balance_sheet1[1:]
            balance_sheet1.columns = new_header1
            new_header2 = balance_sheet2.iloc[0]
            balance_sheet2 = balance_sheet2[1:]
            balance_sheet2.columns = new_header2
            shareholder_equity = balance_sheet2["Total Shareholders' Equity"]
            shareholder_equity = shareholder_equity.to_frame()
            longterm_debt = balance_sheet2["Long-Term Debt"]
            longterm_debt = longterm_debt.to_frame()
            total_assets = balance_sheet1["Total Assets"]
            total_assets = total_assets.to_frame()
            b_s=shareholder_equity.join(longterm_debt)
            b_s = b_s.join(total_assets)
            b_s = b_s.rename(columns={"Total Shareholders' Equity":'shareholder_equity', 'Long-Term Debt':'longterm_debt', "Total Assets": 'total_assets'})
            b_s=b_s.drop('5-year trend')

            financials=i_s.merge(b_s, left_index=True, right_index=True)

            financials['net_income']= financials['net_income'].apply(lambda x: x.replace('.', ''))
            financials['net_income']= financials['net_income'].apply(lambda x: x.replace('B', '0000000'))
            financials['net_income']= financials['net_income'].apply(lambda x: x.replace('M', '000000'))
            financials['interest_expense']= financials['interest_expense'].apply(lambda x: x.replace('.', ''))
            financials['interest_expense']= financials['interest_expense'].apply(lambda x: x.replace('B', '0000000'))
            financials['interest_expense']= financials['interest_expense'].apply(lambda x: x.replace('M', '000000'))
            financials['ebitda']= financials['ebitda'].apply(lambda x: x.replace('.', ''))
            financials['ebitda']= financials['ebitda'].apply(lambda x: x.replace('B', '0000000'))
            financials['ebitda']= financials['ebitda'].apply(lambda x: x.replace('M', '000000'))
            financials['shareholder_equity']= financials['shareholder_equity'].apply(lambda x: x.replace('.', ''))
            financials['shareholder_equity']= financials['shareholder_equity'].apply(lambda x: x.replace('B', '0000000'))
            financials['shareholder_equity']= financials['shareholder_equity'].apply(lambda x: x.replace('M', '000000'))
            financials['longterm_debt']= financials['longterm_debt'].apply(lambda x: x.replace('.', ''))
            financials['longterm_debt']= financials['longterm_debt'].apply(lambda x: x.replace('B', '0000000'))
            financials['longterm_debt']= financials['longterm_debt'].apply(lambda x: x.replace('M', '000000'))
            financials['total_assets']= financials['total_assets'].apply(lambda x: x.replace('.', ''))
            financials['total_assets']= financials['total_assets'].apply(lambda x: x.replace('B', '0000000'))
            financials['total_assets']= financials['total_assets'].apply(lambda x: x.replace('M', '000000'))
            #
            financials['outstanding_shares']= financials['outstanding_shares'].apply(lambda x: x.replace('.', '')) #
            financials['outstanding_shares']= financials['outstanding_shares'].apply(lambda x: x.replace('B', '0000000')) #
            financials['outstanding_shares']= financials['outstanding_shares'].apply(lambda x: x.replace('M', '000000')) #
            financials['ebitda_growth_rate']= financials['ebitda_growth_rate'][1:].apply(lambda x:x.replace('%','')) #

            #financials = financials.apply(lambda x: x.replace('-', 0))#np.nan
            financials = financials.apply(lambda x: x.str.replace('(', '-'))
            financials = financials.apply(lambda x: x.str.strip(')'))
            financials = financials.apply(lambda x: x.replace('-', 0))
            financials = financials.apply(lambda x: x.str.strip('%'))

            financials['eps_growth'] = financials['eps_growth'].astype(float)
            financials['eps'] = financials['eps'].astype(float)
            financials['net_income'] = financials['net_income'].astype(int)
            financials['interest_expense'] = financials['interest_expense'].astype(int)
            financials['ebitda'] = financials['ebitda'].astype(int)
            financials['shareholder_equity'] = financials['shareholder_equity'].astype(int)
            financials['longterm_debt'] = financials['longterm_debt'].astype(int)
            financials['total_assets'] = financials['total_assets'].astype(int)
            #
            financials['outstanding_shares']=financials['outstanding_shares'].astype(int) #
            financials['ebitda_growth_rate']=financials['ebitda_growth_rate'][1:].astype(float) #

            stock_pricing = data_pull(f'{ticker}') #
            stock_price = stock_pricing['Close'] #
            #stock_price = stock_price[0]  #
            
            financials['roa']=financials['net_income']/financials['total_assets']
            financials['roe']=financials['net_income']/financials['shareholder_equity']
            financials['interestcoverageratio']=financials['ebitda']/financials['interest_expense']
            
            last_year=int(financials.index[4])
            cur_year=last_year+1
            current_year = pd.DataFrame(columns=financials.columns, index=[str(cur_year)])
            financials = financials.append(current_year)
            
            financials['pe'] = np.nan
            financials['pb'] = np.nan
            financials['peg'] = np.nan
        
            # PE Ratio
            #financials['pe']=stock_price/financials['eps'][4]
            financials.pe.iloc[0]=stock_price[5]/financials['eps'][0]
            financials.pe.iloc[1]=stock_price[4]/financials['eps'][1]
            financials.pe.iloc[2]=stock_price[3]/financials['eps'][2]
            financials.pe.iloc[3]=stock_price[2]/financials['eps'][3]
            financials.pe.iloc[4]=stock_price[1]/financials['eps'][4]
            financials.pe.iloc[5]=stock_price[0]/financials['eps'][4]
            
            # PB Ratio
            #financials['pb']=stock_price/(financials['shareholder_equity'][4]/financials['outstanding_shares'][4])
            financials.pb.iloc[0]=stock_price[5]/(financials['shareholder_equity'][0]/financials['outstanding_shares'][0])
            financials.pb.iloc[1]=stock_price[4]/(financials['shareholder_equity'][1]/financials['outstanding_shares'][1])
            financials.pb.iloc[2]=stock_price[3]/(financials['shareholder_equity'][2]/financials['outstanding_shares'][2])
            financials.pb.iloc[3]=stock_price[2]/(financials['shareholder_equity'][3]/financials['outstanding_shares'][3])
            financials.pb.iloc[4]=stock_price[1]/(financials['shareholder_equity'][4]/financials['outstanding_shares'][4])
            financials.pb.iloc[5]=stock_price[0]/(financials['shareholder_equity'][4]/financials['outstanding_shares'][4])
            
            #PEG Ratio
            financials.peg.iloc[5]=financials.pe.iloc[5]/financials['ebitda_growth_rate'][1:].mean() #
            
            #financials['pe'][0:4]=np.nan #
            #financials['pb'][0:4]=np.nan #
            #financials['peg'][0:4]=np.nan #
         
            financials = financials.apply(lambda x: x.replace(0, np.nan))
            financials = financials.apply(lambda x: x.replace(np.inf, np.nan))

            financials['ticker'] = f'{ticker}'
            print(ticker)
            financials_list.append(financials)
        except:
            trouble_stocks.append(ticker)

In [302]:
financials_list=[]
collected_stocks=[]
trouble_stocks=[]

In [305]:
financial_scrubber(['ABT'])

ABT

In [300]:
financials_list[0]

,eps,eps_growth,net_income,interest_expense,ebitda,outstanding_shares,ebitda_growth_rate,shareholder_equity,longterm_debt,total_assets,roa,roe,interestcoverageratio,pe,pb,peg,ticker
2015,2.26,NaN,1.760000e+09,217000000.0,4.200000e+08,777000000.0,NaN,2.377000e+10,7.410000e+09,3.924000e+10,0.044852,0.074043,1.935484,19.646018,1.451359,NaN,CCL
2016,3.73,65.04,2.780000e+09,223000000.0,4.810000e+09,745000000.0,14.50,2.260000e+09,8.360000e+09,3.894000e+10,0.071392,1.230088,21.569507,13.150134,16.169137,NaN,CCL
2017,3.61,-3.22,2.610000e+09,198000000.0,5.050000e+09,722000000.0,4.97,2.422000e+10,6.990000e+09,4.078000e+10,0.064002,0.107762,25.505051,17.326870,1.864620,NaN,CCL
2018,4.45,23.27,3.150000e+09,194000000.0,5.340000e+09,709000000.0,5.82,2.444000e+10,7.900000e+08,4.240000e+09,0.742925,0.128887,27.525773,14.170787,1.829359,NaN,CCL
2019,4.33,-2.62,2.990000e+09,222000000.0,5.440000e+09,690000000.0,1.78,2.537000e+10,9.680000e+09,4.506000e+10,0.066356,0.117856,24.504505,12.570439,1.480359,NaN,CCL
2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.854504,0.453926,0.569561,CCL

In [248]:
def warnings(financial_dfs):
    
    eligiblestock = True
    warninglist=[]
  
    for df in financial_dfs:
        print(df.ticker.values[0])
        display(df)
        # EPS increases over the year (consistent)
        for growth in df.eps_growth:
            #print(growth)
            if growth<0:
                print('Growth Warning')
                eligiblestock = False
                warninglist.append('Negative Growth')
                break
        # ROE > 0.13
        if df.roe.mean()<0.13:
            print('ROE Warning')
            eligiblestock = False
            warninglist.append('ROE mean is insufficient')
        # ROA > 0.07 (also consider debt to equity cause Assets = liabilities + equity)         
        if df.roa.mean()<0.07:
            print('ROA Warning')
            eligiblestock = False
            warninglist.append('ROA mean is insufficient')
        # Long term debt < 5 * income
        for ltd in df.longterm_debt.tail(1):
            if ltd > 5*df.net_income.tail(1).values[0]:
                print('Longterm Debt Warning')
                eligiblestock = False
                warninglist.append('Longterm Debt is too high compared to net income')
        # Interest Coverage Ratio > 3
        for icr in df.interestcoverageratio.tail(1):
            if icr < 3:
                print('Interest Coverage Ratio Warning')
                eligiblestock = False
                warninglist.append('Interest Coverage Ratio is insufficient.')
        for peg in df.peg.tail(1):
            if peg > 1:
                print('PEG Warning')
                eligiblestock = False
                warninglist.append('PEG Ratio is insufficient.')
        print (f'\nEligible Stock = {eligiblestock}')
        print('\nReasons:')
    return warninglist

In [293]:
warnings(financials_list)

CCL

,eps,eps_growth,net_income,interest_expense,ebitda,outstanding_shares,ebitda_growth_rate,shareholder_equity,longterm_debt,total_assets,roa,roe,interestcoverageratio,pe,pb,peg,ticker
2015,2.26,NaN,1.760000e+09,217000000.0,4.200000e+08,777000000.0,NaN,2.377000e+10,7.410000e+09,3.924000e+10,0.044852,0.074043,1.935484,19.646018,1.451359,NaN,CCL
2016,3.73,65.04,2.780000e+09,223000000.0,4.810000e+09,745000000.0,14.50,2.260000e+09,8.360000e+09,3.894000e+10,0.071392,1.230088,21.569507,13.150134,16.169137,NaN,CCL
2017,3.61,-3.22,2.610000e+09,198000000.0,5.050000e+09,722000000.0,4.97,2.422000e+10,6.990000e+09,4.078000e+10,0.064002,0.107762,25.505051,17.326870,1.864620,NaN,CCL
2018,4.45,23.27,3.150000e+09,194000000.0,5.340000e+09,709000000.0,5.82,2.444000e+10,7.900000e+08,4.240000e+09,0.742925,0.128887,27.525773,14.170787,1.829359,NaN,CCL
2019,4.33,-2.62,2.990000e+09,222000000.0,5.440000e+09,690000000.0,1.78,2.537000e+10,9.680000e+09,4.506000e+10,0.066356,0.117856,24.504505,12.570439,1.480359,NaN,CCL
2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.854504,0.453926,0.569561,CCL

Growth Warning

Eligible Stock = False

Reasons:

['Negative Growth']

In [ ]:
pip install numpy-financial

In [98]:
import numpy_financial as npf

In [294]:
dfprice = pd.DataFrame(columns =['ticker','annualgrowthrate','last_eps','future_eps'])

In [295]:
for f in financials_list:
    #print(f.eps.iloc[0])
    #print(f.eps.iloc[-2])
    annualgrowthrate =  npf.rate(4, 0, -1*f.eps.iloc[0], f.eps.iloc[-2])
    agr =  f.eps_growth.mean()*.01 #growth rate
    print(agr)
    print(annualgrowthrate)
    ###
    #last_eps = f.eps.tail(2).values[0] #presentvalue
    last_eps = f.eps.mean()
    print(last_eps)
    years  = 10 #period
    future_eps = abs(npf.fv(agr,years,0,last_eps))
    print(future_eps)
    
    dfprice.loc[0] = [f.ticker[0],agr,last_eps,future_eps]
    #### 
    min_eps= f.pe.min()

    dfprice['pe_ratio'] = min_eps

    dfprice['FV'] = dfprice['future_eps']*dfprice['pe_ratio']

    discountrate=.15
    margin=.15

    ticker=f.ticker[0]
    stock_pricing = data_pull(f'{ticker}') #
    stock_price = stock_pricing['Close'] #
    cur_stock_price = stock_price[0]
    print(cur_stock_price)
    ###
    dfprice['PV'] = abs(np.pv(discountrate,years,0,fv=dfprice['FV']))

    if dfprice['FV'].values[0] > 0:
        dfprice['marginprice'] = dfprice['PV']*(1-margin)
    else:
        dfprice['marginprice'] = 0

    dfprice['lastshareprice']=cur_stock_price
    
    print(dfprice)
    
    if dfprice['lastshareprice'][0]<dfprice['marginprice'][0]:
        dfprice['decision'] = 'Buy'
    else: 
        dfprice['decision'] = 'Sell'

    #return dfprice

0.206175
0.17650794492811525
3.6760000000000006
23.959554035917275
16.690000534057617
  ticker  annualgrowthrate  last_eps  future_eps  pe_ratio         FV  \
0    CCL          0.206175     3.676   23.959554  3.854504  92.352187

          PV  marginprice  lastshareprice
0  22.828048    19.403841       16.690001

/Users/eharacz/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:33: DeprecationWarning: numpy.pv is deprecated and will be removed from NumPy 1.20. Use numpy_financial.pv instead (https://pypi.org/project/numpy-financial/).

In [296]:
dfprice

,ticker,annualgrowthrate,last_eps,future_eps,pe_ratio,FV,PV,marginprice,lastshareprice,decision
0,CCL,0.206175,3.676,23.959554,3.854504,92.352187,22.828048,19.403841,16.690001,Buy

In [ ]:
financial_scrubber(tickers_marketwatch)

In [ ]:
financials_list[1]

In [ ]:
len(trouble_stocks)

In [ ]:
len(financials_list)

Some financial statments are not standardized so the function will only work on those that is standardized

## --------- Example of why it doesnt get all stock financials

In [ ]:
test = pd.read_html('https://www.marketwatch.com/investing/stock/afl/financials')
tester = pd.DataFrame(test[1])

In [ ]:
tester
tester = tester.transpose()
new_header = tester.iloc[0]
tester = tester[1:]
tester.columns = new_header

In [ ]:
tester

In [ ]:
pagey = pd.read_html('https://www.zacks.com/stock/quote/ABT')

In [ ]:
pagey[2]